import { Equipment, EquipmentCategory } from './equipment.model';

export const EQUIPMENT_CATEGORIES: EquipmentCategory[] = [
  { id: 8, name: 'Chapiteaux', color: '#0d9488' },
  {
    id: 1,
    name: 'Chaise',
    color: '#2563eb',
  },
  {
    id: 2,
    name: 'Table',
    color: '#7c3aed',
  },
  {
    id: 3,
    name: 'Bougeoir',
    color: '#d97706',
  },
  {
    id: 4,
    name: 'Vaisselle',
    color: '#0891b2',
  },
  {
    id: 5,
    name: 'Tapis et accessoires',
    color: '#db2777',
  },
  {
    id: 6,
    name: 'Chauffe-plat',
    color: '#ea580c',
  },
  {
    id: 7,
    name: 'Décoration florale',
    color: '#16a34a',
  },
];

export const INITIAL_EQUIPMENT: Equipment[] = [
  {
    id: 1,
    code: 'MAT-001',
    categoryId: 1,
    designation: 'Chaise Napoléon dorée',
    price: 5000,
    reimbursement: 150000,
    photo: 'assets/chaise_napoleon_dore.jpg',
  },
  {
    id: 2,
    code: 'MAT-002',
    categoryId: 1,
    designation: 'Chaise Napoléon argentée',
    price: 5000,
    reimbursement: 150000,
    photo: 'assets/chaise_napoleon_argentee.png',
  },
  {
    id: 3,
    code: 'MAT-003',
    categoryId: 1,
    designation: 'Chaise simple en plastique',
    price: 1500,
    reimbursement: 40000,
    photo: 'assets/chaise_blanche.jpg',
  },
  {
    id: 4,
    code: 'MAT-004',
    categoryId: 1,
    designation: 'Chaise des mariés',
    price: 25000,
    reimbursement: 500000,
    photo: 'assets/chaises_maries.jpg',
  },
  {
    id: 5,
    code: 'MAT-005',
    categoryId: 1,
    designation: 'Chaise pliable',
    price: 3000,
    reimbursement: 80000,
    photo: 'assets/chaise_pliable.jpg',
  },
  {
    id: 6,
    code: 'MAT-006',
    categoryId: 2,
    designation: 'Table ronde – 8 personnes',
    price: 18000,
    reimbursement: 300000,
    photo: 'assets/table_ronde_8_personnes.jpg',
  },
  {
    id: 7,
    code: 'MAT-007',
    categoryId: 2,
    designation: 'Table ronde – 10 personnes',
    price: 22000,
    reimbursement: 380000,
    photo: 'assets/table_ronde_10_personnes.jpg',
  },
  {
    id: 8,
    code: 'MAT-008',
    categoryId: 2,
    designation: 'Table rectangulaire – 8 personnes',
    price: 15000,
    reimbursement: 250000,
    photo: 'assets/table_rectangulaire_8_personnes.jpg',
  },
  {
    id: 9,
    code: 'MAT-009',
    categoryId: 2,
    designation: 'Table rectangulaire – 10 personnes',
    price: 18000,
    reimbursement: 300000,
    photo: 'assets/table_rectangulaire_10_personnes.jpg',
  },
  {
    id: 10,
    code: 'MAT-010',
    categoryId: 3,
    designation: 'Bougeoir simple',
    price: 2000,
    reimbursement: 25000,
    photo: 'assets/chandelier_dore.jpg',
  },
  {
    id: 11,
    code: 'MAT-011',
    categoryId: 3,
    designation: 'Chandelier à 3 branches',
    price: 5000,
    reimbursement: 70000,
    photo: 'assets/chandelier_3_branches.jpg',
  },
  {
    id: 12,
    code: 'MAT-012',
    categoryId: 3,
    designation: 'Chandelier à 5 branches',
    price: 8000,
    reimbursement: 120000,
    photo: 'assets/chandelier_5_branches.jpg',
  },
  {
    id: 13,
    code: 'MAT-013',
    categoryId: 3,
    designation: 'Bougeoir haut en verre',
    price: 6000,
    reimbursement: 80000,
    photo: null,
  },
  {
    id: 14,
    code: 'MAT-014',
    categoryId: 3,
    designation: 'Bougeoir doré sur pied',
    price: 7000,
    reimbursement: 100000,
    photo: null,
  },
  {
    id: 15,
    code: 'MAT-015',
    categoryId: 3,
    designation: 'Photophore en verre',
    price: 1500,
    reimbursement: 20000,
    photo: null,
  },
  {
    id: 16,
    code: 'MAT-016',
    categoryId: 4,
    designation: 'Assiette plate',
    price: 500,
    reimbursement: 8000,
    photo: 'assets/assiette_plate.jpg',
  },
  {
    id: 17,
    code: 'MAT-017',
    categoryId: 4,
    designation: 'Assiette creuse',
    price: 500,
    reimbursement: 8000,
    photo: 'assets/assiette_creuse.jpg',
  },
  {
    id: 18,
    code: 'MAT-018',
    categoryId: 4,
    designation: 'Assiette à dessert',
    price: 400,
    reimbursement: 6000,
    photo: null,
  },
  {
    id: 19,
    code: 'MAT-019',
    categoryId: 4,
    designation: 'Verre à eau',
    price: 400,
    reimbursement: 5000,
    photo: 'assets/verre_a_eau.jpg',
  },
  {
    id: 20,
    code: 'MAT-020',
    categoryId: 4,
    designation: 'Verre à vin',
    price: 600,
    reimbursement: 8000,
    photo: 'assets/verre_a_vin.jpg',
  },
  {
    id: 21,
    code: 'MAT-021',
    categoryId: 4,
    designation: 'Cuillère',
    price: 300,
    reimbursement: 3000,
    photo: 'assets/cuillere_argentee.jpg',
  },
  {
    id: 22,
    code: 'MAT-022',
    categoryId: 4,
    designation: 'Fourchette',
    price: 300,
    reimbursement: 3000,
    photo: 'assets/fourchette_argentee.jpg',
  },
  {
    id: 23,
    code: 'MAT-023',
    categoryId: 4,
    designation: 'Couteau',
    price: 400,
    reimbursement: 5000,
    photo: 'assets/couteau_argente.jpg',
  },
  {
    id: 24,
    code: 'MAT-024',
    categoryId: 5,
    designation: 'Tapis rouge',
    price: 40000,
    reimbursement: 500000,
    photo: null,
  },
  {
    id: 25,
    code: 'MAT-025',
    categoryId: 5,
    designation: 'Tapis blanc',
    price: 45000,
    reimbursement: 550000,
    photo: null,
  },
  {
    id: 26,
    code: 'MAT-026',
    categoryId: 5,
    designation: 'Potelet doré',
    price: 15000,
    reimbursement: 250000,
    photo: null,
  },
  {
    id: 27,
    code: 'MAT-027',
    categoryId: 5,
    designation: 'Potelet argenté',
    price: 15000,
    reimbursement: 250000,
    photo: null,
  },
  {
    id: 28,
    code: 'MAT-028',
    categoryId: 5,
    designation: 'Cordon rouge pour potelet',
    price: 5000,
    reimbursement: 70000,
    photo: 'assets/cordon_rouge_potelet.jpg',
  },
  {
    id: 29,
    code: 'MAT-029',
    categoryId: 5,
    designation: 'Cordon doré pour potelet',
    price: 6000,
    reimbursement: 80000,
    photo: 'assets/cordon_dore_potelet.jpg',
  },
  {
    id: 30,
    code: 'MAT-030',
    categoryId: 6,
    designation: 'Chauffe-plat ovale',
    price: 25000,
    reimbursement: 450000,
    photo: 'assets/chauffe_plat_ovale.jpg',
  },
  {
    id: 31,
    code: 'MAT-031',
    categoryId: 6,
    designation: 'Chauffe-plat rectangulaire',
    price: 25000,
    reimbursement: 450000,
    photo: 'assets/chauffe_plat_rectangulaire.jpg',
  },
  {
    id: 32,
    code: 'MAT-032',
    categoryId: 6,
    designation: 'Chauffe-plat rond',
    price: 22000,
    reimbursement: 400000,
    photo: 'assets/chauffe_plat_rond.jpg',
  },
  {
    id: 33,
    code: 'MAT-033',
    categoryId: 6,
    designation: 'Chauffe-plat double bac',
    price: 35000,
    reimbursement: 600000,
    photo: 'assets/chauffe_plat_double_bac.jpg',
  },
  {
    id: 34,
    code: 'MAT-034',
    categoryId: 6,
    designation: 'Chauffe-plat électrique',
    price: 40000,
    reimbursement: 700000,
    photo: 'assets/chauffe_plat_electrique.jpg',
  },
  {
    id: 35,
    code: 'MAT-035',
    categoryId: 6,
    designation: 'Chauffe-plat avec couvercle vitré',
    price: 35000,
    reimbursement: 650000,
    photo: 'assets/chauffe_plat_couvercle_vitre.jpg',
  },
  {
    id: 36,
    code: 'MAT-036',
    categoryId: 7,
    designation: 'Porte-bouquet doré',
    price: 12000,
    reimbursement: 180000,
    photo: 'assets/porte_bouquet_dore.jpg',
  },
  {
    id: 37,
    code: 'MAT-037',
    categoryId: 7,
    designation: 'Porte-bouquet argenté',
    price: 12000,
    reimbursement: 180000,
    photo: 'assets/porte_bouquet_argente.jpg',
  },
  {
    id: 38,
    code: 'MAT-038',
    categoryId: 7,
    designation: 'Porte-bouquet haut',
    price: 15000,
    reimbursement: 220000,
    photo: null,
  },
  {
    id: 39,
    code: 'MAT-039',
    categoryId: 7,
    designation: 'Colonne pour bouquet',
    price: 20000,
    reimbursement: 300000,
    photo: 'assets/colonne_bouquet_blanc.jpg',
  },
  {
    id: 40,
    code: 'MAT-040',
    categoryId: 7,
    designation: 'Vase décoratif',
    price: 8000,
    reimbursement: 100000,
    photo: 'assets/vase_decoratif.jpg',
  },
  {
    id: 41,
    code: 'MAT-041',
    categoryId: 7,
    designation: 'Composition florale artificielle',
    price: 15000,
    reimbursement: 200000,
    photo: 'assets/composition_florale_artificielle.jpg',
  },
  {
    id: 42,
    code: 'MAT-042',
    categoryId: 8,
    designation: 'Chapiteaux 3 x 3',
    price: 50000,
    reimbursement: 1000000,
    photo: 'assets/chapiteaux.jpg',
  },
  {
    id: 43,
    code: 'MAT-043',
    categoryId: 8,
    designation: 'Pagode 3 x 6',
    price: 100000,
    reimbursement: 2000000,
    photo: 'assets/pagode.jpg',
  },
];
